### ISSUE TITLE
Doesn't compile with tgvoip-dev 2.4.2-1

### ISSUE THREAD

**Issue by rudolfkral** [ars3niy/tdlib-purple#153]
When compiling on Debian with `tgvoip-dev`, package version 2.4.2-1(most recent), the following error appears:

```
(...)/tdlib-purple-0.8.1/call.cpp: In function ‘bool activateCall(const td::td_api::call&, const string&, TdAccountData&, TdTransceiver&)’:
(...)/tdlib-purple-0.8.1/call.cpp:121:57: error: cannot bind non-const lvalue reference of type ‘tgvoip::IPv4Address&’ to an rvalue of type ‘tgvoip::IPv4Address’
                                                 tgvoip::IPv4Address(pServer->ip_address_),
                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

VoIP isn't very important to me, so that's not a big issue, but I'm curious, what version are you using that's compatible? Does anyone else have that problem?

**Comment by BenWiederhake** [comment]
As a temporary workaround, you can use `-DNoVoip=True` in cmake.

(In case you're curious: I never tried to get tdlib-purple to work with tgvoip, so I don't know whether that's actually possible.)

**Comment by rudolfkral** [comment]
> As a temporary workaround, you can use `-DNoVoip=True` in cmake.

Thanks, I did that and everything seems to be working.

> (In case you're curious: I never tried to get tdlib-purple to work with tgvoip, so I don't know whether that's actually possible.)

Interesting! I wonder if anybody used it.
