### ISSUE TITLE
Building on ubuntu 16.04

### ISSUE THREAD

**Issue by tobozo** [ars3niy/tdlib-purple#93]
Hello and thanks for this project :+1: 

Not really an issue since I managed to build the plugin, but I'll share what I had to do to get it working on an old Ubuntu 16.04

1) `tdlib version 1.6.5 or older is required` -> had to disable $TDLIB_VERSION_NUMBER version check in CMakelist.txt because I could not find such version
2) I used tdlib v1.6.0
3) ` error: ‘isfinite’ was not declared in this scope` -> had to edit purple-info.cpp to change `isfinite` to `std::isfinite` 

Maybe those steps are trivial or just symptomatic of the Ubuntu version, but since I spent a few hours finding that out I thought it might be worth sharing.

Feel free to close if this is irrelevant or out of scope, thanks again for this great project!

**Comment by ars3niy** [comment]
Both these problems are beyond me as 1.6.0 is indeed **older** than 1.6.5 and isfinite is supposed to be present in math.h

**Comment by tobozo** [comment]
probably a side effect of time travel :-)

- GNU make version 4.1
- cmake version 3.5.2
- clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
- gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~16.04)

**Comment by ars3niy** [comment]
Turns out <cmath> doesn't just add std::isfinite, it un-defines the original isfinite which is a macro. Why is it a macro and not a static function in the header, I will never know.
