### ISSUE TITLE
FTBFS -- some td_api methods seem to don't exist anymore

### ISSUE THREAD

**Issue by fulalas** [ars3niy/tdlib-purple#106]
Trying to build on Linux x64 using tdlib 1.7.0 I'm seeing this:

> identifiers.h:57:47: error: ‘updateChatChatList’ in namespace ‘td::td_api’ does not name a type; did you mean ‘updateChatFilters’?

Maybe I'm doing something wrong, but in the changelog of tdlib 1.7.0 it says:
> Removed the superfluous updates `updateChatChatList`, `updateChatIsSponsored`, `updateChatOrder` and
    `updateChatIsPinned`.

Maybe that's the reason tdlib-purple is failing to find these methods when building?

**Comment by ars3niy** [comment]
Yes, there's a reason there's supposed to be a message that "tdlib version 1.6.5 or older is required" and you would have to disable it. tdlib doesn't maintain backwards compatibility.

**Comment by fulalas** [comment]
I see. I actually removed the version check from cmakelists file thinking that was just and old check :P

Just one more question. I couldn't find tdlib 1.6.5, only 1.6.0. You know why?

Thanks!

**Comment by ars3niy** [comment]
They don't make tags for those intermediate versions, it can only be found in commit history. Although there's nothing wrong with 1.6.0

**Comment by ars3niy** [comment]
Now version requirement is >=1.7.8 by the way

**Comment by fulalas** [comment]
Amazing job! Thank you very much! :)
